function Explore() {
  return (
    <div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
      <div>EXPLORE SONG PAGE</div>
    </div>
  );
}
export default Explore;
